[[time_slots]]
name = "Meth"
date = "2025-11-03"
time = "00:00:00"
time_zone = "UTC"

[[time_slots]]
name = "Try"
date = "2025-11-03"
time = "03:00:00"
time_zone = "UTC"

[[time_slots]]
name = "Meth"
date = "2028-11-03"
time = "00:00:00"
time_zone = "UTC"

[[time_slots]]
name = "Hans"
date = "2034-10-01"
time = "00:00:00"
time_zone = "UTC"
