[package]
name = "cronplaner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = {version = "0.4.39", features = ["serde"]}
serde = {version = "1.0.217", features = ["derive"]}
toml = "0.8.19"
